FROM ubuntu:jammy
SHELL ["/bin/bash", "-xo", "pipefail", "-c"]

ENV LANG=en_US.UTF-8

ARG TARGETARCH

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        dirmngr \
        fonts-noto-cjk \
        gnupg \
        libssl-dev \
        node-less \
        npm \
        postgresql-client \
        python3-magic \
        python3-num2words \
        python3-odf \
        python3-pdfminer \
        python3-pip \
        python3-phonenumbers \
        python3-pyldap \
        python3-qrcode \
        python3-renderpm \
        python3-setuptools \
        python3-slugify \
        python3-vobject \
        python3-watchdog \
        python3-xlrd \
        python3-xlwt \
        xz-utils && \
    if [ -z "${TARGETARCH}" ]; then \
        TARGETARCH="$(dpkg --print-architecture)"; \
    fi; \
    WKHTMLTOPDF_ARCH=${TARGETARCH} && \
    case ${TARGETARCH} in \
    "amd64") WKHTMLTOPDF_ARCH=amd64 ;; \
    "arm64") WKHTMLTOPDF_ARCH=arm64 ;; \
    esac \
    && curl -o wkhtmltox.deb -sSL https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.jammy_${WKHTMLTOPDF_ARCH}.deb \
    && apt-get install -y --no-install-recommends ./wkhtmltox.deb \
    && rm -rf /var/lib/apt/lists/* wkhtmltox.deb

RUN npm install -g rtlcss

ENV ODOO_VERSION={{.OdooVersion}}
ARG ODOO_RELEASE=latest
ARG ODOO_SHA=skip
RUN if [ "$ODOO_RELEASE" = "latest" ]; then \
        ODOO_RELEASE=$(curl -s https://nightly.odoo.com/${ODOO_VERSION}/nightly/deb/ | grep -oE "odoo_${ODOO_VERSION}\.[0-9]+_all\.deb" | sort -V | tail -1 | sed "s/odoo_${ODOO_VERSION}\.\(.*\)_all\.deb/\1/"); \
    fi && \
    curl -o odoo.deb -sSL http://nightly.odoo.com/${ODOO_VERSION}/nightly/deb/odoo_${ODOO_VERSION}.${ODOO_RELEASE}_all.deb && \
    if [ "$ODOO_SHA" != "skip" ]; then \
        echo "${ODOO_SHA} odoo.deb" | sha1sum -c -; \
    fi && \
    apt-get update && \
    apt-get -y install --no-install-recommends ./odoo.deb && \
    rm -rf /var/lib/apt/lists/* odoo.deb

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    vim \
    htop \
    openssh-client \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir \
    debugpy \
    ipython \
    lxml_html_clean{{if .PipPackages}} \
    {{.PipPackages}}{{end}}

{{if .Enterprise}}
# Clone Odoo Enterprise
{{if .EnterpriseGitHubToken}}
# Using GitHub Personal Access Token
RUN git clone --depth 1 --branch {{.OdooVersion}} \
    https://{{.EnterpriseGitHubToken}}@github.com/odoo/enterprise.git /mnt/enterprise && \
    chown -R odoo:odoo /mnt/enterprise && \
    chmod -R 755 /mnt/enterprise
{{else}}
# Using SSH keys
RUN --mount=type=ssh git clone --depth 1 --branch {{.OdooVersion}} \
    git@github.com:odoo/enterprise.git /mnt/enterprise && \
    chown -R odoo:odoo /mnt/enterprise && \
    chmod -R 755 /mnt/enterprise
{{end}}
{{end}}

COPY ./entrypoint.sh /
COPY ./wait-for-psql.py /usr/local/bin/wait-for-psql.py

RUN chown odoo /etc/odoo/odoo.conf \
    && mkdir -p /mnt/extra-addons \
    && chown -R odoo /mnt/extra-addons \
    && mkdir -p /var/lib/odoo/.local/share/Odoo/sessions \
    && mkdir -p /var/lib/odoo/filestore \
    && chown -R odoo:odoo /var/lib/odoo \
    && chmod -R 755 /var/lib/odoo \
    && chmod +x /entrypoint.sh \
    && chmod +x /usr/local/bin/wait-for-psql.py

VOLUME ["/var/lib/odoo", "/mnt/extra-addons"]

EXPOSE 8069 8071 8072 5678

ENV ODOO_RC=/etc/odoo/odoo.conf

USER odoo

WORKDIR /mnt/extra-addons

ENTRYPOINT ["/entrypoint.sh"]
CMD ["odoo"]
